---
title: "Exploratory Data Analysis using R"
engine: knitr
---

```{r}
#| class-output: outputcode
#| eval: true
#| include: false
library(tidyverse)
```

Data are being generated on a huge scale in every area of our lives. How do we extract valuable information and draw meaningful conclusions from data? The term *data analytics* is often used in place of the term *statistics*. Statistics (data analytics) is the science of learning from data that gives us the tools to answer interesting questions!

## Data collection

The data collection process is the MOST important step but is often ignored or given little thought. Data tend to be collected in a very ad hoc way, without thinking about the problem at hand. There is **nothing** data analytics (or statistics or machine learning or AI!) can do if the data are poor quality.

## Descriptive statistics 

Also called *exploratory analysis*. Creates simple summaries of the data to describe and understand the data, and how the variables relate to one another. 

Consists of two parts:  

1. Data visualisation 
2. Numerical summaries (e.g. mean, median, standard deviation, variance, etc.)


## Statistical inference

Statistical inference means interpreting and drawing conclusions from the data in the presence of variability.

Generalising the results.

Uses hypothesis testing, confidence intervals, predictive modelling, etc.

## Goal

Have sets of variables that have something in common but differ from individual to individual.

Different values  => *variability*.

Variability can obscure the patterns (signal) which are of interest to us. 

Statistics helps us to distinguish the pattern (signal) from the variability (noise).


## Sources of variability

There are two main sources of variability.

- **Natural variation**: e.g. genetic, environmental. Try to average out sources of variation that we cannot control by carrying out data collection in a well-planned way.
- **Measurement process variation**: e.g. rounding error, instrumentation may not be sensitive enough, human error, etc.

## Additional resources
