# Assessment

## Description


In order to receive credit for the course, each person must complete a project about a selected problem using R. A project may be undertaken by a group of 1-3 people. The recommended group size is 2. The project report and the oral examination shall demonstrate that the intended learning outcomes of the [course](/information/overview.qmd) are reached. 


Please fill this Google sheet for the group project:

<center>[LINK](https://docs.google.com/spreadsheets/d/1f-UrPNahYLqjcTAoHOrhbr95mFoPksRxuwZTlJRRYgc/edit?usp=sharing)</center>



Each person will be required to:

* Give a 5 minutes (group) presentation of her/his problem.

* Hand in a project report and R code.


On Week 2 topics will be selected, and groups will be formed. Ideas for project topics can be seen below. You are free to create you own groups, possibly consisting of one person only. Each group will have time during the lectures to work on the chosen problem. Each group has to present their problem on Week 6 and their final results on Week 11. I will give feedback on Week 12. The purpose of these presentations is for the participants and teacher to influence and inspire each other such that maybe a better report can be written.

## Formal requirements

The project report must be written in English, with an English abstract. Each project must fill at most 15 pages (1 person) or 20 pages (2-3 persons), appendix and source code not included. The report's cover page should include title in English, name(s), student's ID. The project report must be compiled using Quarto or Latex. A Quarto template is available [here](/information/templates/template_quarto.zip) and a Latex template is available [here](/information/templates/template_latex.zip). Program files/code should **not** be included as appendices in the report but be sent as separate files.


## Schedule

**The report must be sent in Friday, November 22 before 5pm**. A pdf-file of the report and source code must be sent by email at **steven.golovkine@ul.ie** with **MS6071** as object.

| Description | Date deadline | Hour deadline |
|:------:|--------:|--------:|
| Proposal presentation | 15/10/24 | 4:00pm |
| Manuscript + Code | 22/11/24 | 5:00pm |


## Grading Criteria

The proposal will be graded on the following criteria:

* Clear statement of objectives and purpose.

* Quality and relevance of sources used.

* Demonstrates a clear understanding of the topic.

* Critical thinking and analysis of the information presented.

* Clear and concise writing.

* Adherence to required formatting guidelines.

* Implementation in R.

* Clean R code.

* Reproducibilty of the R code.


## Late Submission 

No late submission will be accepted. The grade will be decreased by 25% if the submission is handed the same day but late, and by 50% if the submission in handed the next day.


## Examples of project

Below you will find suggestions for topics you may consider in your project. You may also consider other topics. Please consult with me beore the final topic is chosen. In general chose a topic you are familar with. In all cases, you have to provide your analysis in R.


Projects can roughly be put in three categories:

* Pick a dataset and create visualization / Shiny app.

* Pick a research paper and reimplement the analysis.

* Perform a simulation study on a topic of interest. 

Here are some examples of projects:

* For a data-based project:
    - [Weather](https://github.com/taohan10200/WEATHER-5K).
    - [Marine](https://data.marine.copernicus.eu/products).
    - [Anatomy](https://physionet.org/about/database/).
    - [Physics](http://opendata.cern.ch).
    - ...

* For a research-based project:
    - Quantile regression [@soomro2024bayesian].
    - Time series modelling [@shoari2024vector].
    - Missing data [@mcneish2017missing].
    - Functional data [@benkoCommonFunctionalPrincipal2009].
    - ...

* For a simulation-based project:
    - Airline yield-management problems [@lautenbacher1999underlying],[@talluri2004revenue].
    - Optimal prices of a job shop with a single work station [@johansen1991optimal].
    - Study of insurance contract [@palfrey1985repeated].
    - ...


## Last year projects

* Review of global agriculture data for famine and obesity using the programming language R

* EPL data analysis: From raw data to predictive insights

* Cricket data analysis with R

* Statistical analysis of housing in Ireland

* Image classification

* Exploring health and well-being: A comprehensive statistical analysis of health indicators using R


## Miscellaneous

::: {.callout-important}
## Important remarks

* Presence in class is strongly encouraged and the presence will be recorded.

* Plagiarism is presenting another person’s work or ideas as your own. Plagiarism is a serious breach of ethics and is not taken lightly. It undermines academic integrity and it will not be tolerated.

:::

I will carefully consider the student responses to the evaluation of my course and their implications for course development. It is also common practice to discuss informally with students how the course and their mastery of it are progressing. Thank you in advance for your contribution!