# Course support

<br>

Most of you will need help at some point and we want to make sure you can identify when that is without getting too frustrated and feel comfortable seeking help.

## Lectures/Tutorials

If you have a question during lecture/tutorials, feel free to ask it!
There are likely other students with the same question, so by asking you will create a learning opportunity for everyone. 

## Office hours

I am here to help you be successful in the course. You are encouraged to attend office hours during the times posted on the home page to ask questions about the course content and assignments. A lot of questions are most effectively answered in-person, so office hours are a valuable resource. I encourage each and every one of you to take advantage of this resource! Make a pledge to stop by office hours at least once during the first three weeks of class. If you truly have no questions to ask, just stop by and say hi and introduce yourself.

## Email

Please refrain from emailing any course content questions and only use email for questions about personal matters that may not be appropriate for the public course forum (e.g., illness, accommodations, etc.).

If there is a question that's not appropriate for the public forum, you are welcome to email me directly.
**If you email me, please include "MS6071" in the subject line.** Barring extenuating circumstances, I will respond to MS6071 emails within 48 hours Monday - Friday. Response time may be slower for emails sent Friday evening - Sunday.
