---
title: "Tidyverse - Tutorial"
engine: knitr
---

<br>

The aim of the tutorial is to introduce you to the `tidyverse` packages. To accomplish this, we will work with a dataset related to EU Student Mobility, sourced from the [portal for European data](https://data.europa.eu/data/datasets?locale=en&catalog=eac&query=erasmus&page=1&sort=issued%2Bdesc,%20relevance%2Bdesc,%20title.en%2Basc). Detailed information about the dataset can be accessed [here](https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-03-08/readme.md), and it is available for download [here](/labs/ressources/erasmus.csv).

While it is possible to address the questions using R base functions, our focus will be on employing the `tidyverse` packages for these tasks.

## Part 1 - Data importation and cleaning

1. Load the data set.

2. Remove the columns `project_reference`, `activity_mob`, `field_of_education`, `education_level`, `participant_profile`, `sending_organisation_erasmus_code`, `group_leader` and `receiving_organisation_erasmus_code`.

3. Convert the columns `mobility_start_month` and `mobility_end_month` to Date.
 
4. Convert the columns `academic_year` to ordered factor and `participant_nationality`, `participant_gender`, `sending_country_code` and `receiving_country_code` to factor.

5. Convert the columns `special_needs` and`fewer_opportunities` to boolean.

6. Is there any rows with inconsistencies, e.g., negative ages? Remove these rows.


## Part 2 - Data manipulation

7. What is the mean mobility duration?

8. How many people stayed more than 3 months in the UK in the academic year 2015-2016?

9. What are the top 5 countries that receive the most people?

10. How many women went to Ireland during the academic year 2018-2019?

11. Within this subset of the data, what is the proportion of participants that go to Dublin?

12. What is the correlation between the duration of the mobility and the age of the participant by participant nationality. Make sure to have enough data points estimate the correlation (let say more than 100).


## Part 3 - Plots

For all the questions regarding the plots, make sure to set proper axis, titles, themes and other visual elements.

13. Plot the distribution of participant ages (regardless the number of participants).

14. Plot the distribution of the ages by nationality and by gender. Create a grid for the different nationalities and have a different color for the gender. Select some nationalities to simplify the plot.

15. Plot the evolution of the number of participants through academic year for the top 5 countries that received the most participants.

16. Plot the alluvial plot between the sending and receiving country by participant gender. To ease the visualisation, remove the rows where the receiving country is the sending country and only consider links with more than 50 participants. (You may need to install another package.)

17. Propose your own plot using this dataset.

<br><br>

::: {style="font-size: 0.875em;"}
[Back](/weeks/week-2.qmd) ⏎
:::