---
title: "Simulation - Tutorial"
engine: knitr
---

<br>
The aim of the tutorial is to manipulate different simulation scenarios.


## The inverse transform method

1. Let $f : x \in (0, 1/2) \to 1/\sqrt{2x}$ be a probability density function of a random variable $X$. Generate using the inverse transform method a sample of size 100 of $X$.

2. Generate a sample from the cumulative density function $F(x)=1- \exp(-\exp((x-\mu)/\sigma))$. Compare the empirical cumulative density function of the generated sample with $F$.

## Using R functions

3. Plot the probability density function of a Student distribution with varying parameters. Generate a sample of data with a $t(5)$ distribution, compute the empirical cumulative density function and compare it to the true one.

## Composition method

Let $X_1 \sim \Gamma(2,2)$ and $X_2 \sim \Gamma(2,4)$ be independent.
The probability density function of $X_i$ $(i=1,2)$ is denoted by $f_i$.

4. Generate a sample of size $100$ from $Y_1 = (X_1+X_2)/2$.

5. Let $Y_2$ be a random variable of pdf $\frac{1}{2} f_1 + \frac{1}{2} f_2$. Generate a sample of size 100 from $Y_2$.

6. Compare the sampling distribution of $Y_1$ and $Y_2.$

## Model simulation

7. Generate some data using this model:

$$ Y = \beta_0 + \beta_1 x^2 + \beta_2 \log(x) + \epsilon,$$

where $\epsilon = \mathcal{N}(0, 1)$. Fix $\beta_0 = 4$, $\beta_1 = 0.3$ and $\beta_2 = 2$.
Generate $X \sim \mathcal{U}(1, 5)$. Plot the data. Fit a linear and try to retrieve the coefficients.

8. Generate some data using this model:

$$ Y \sim \mathcal{B}(p), \quad\text{where}\quad p = xz.$$

Generate $X \sim \mathcal{U}(0, 1)$ and $Z \sim \mathcal{U}(0, 1)$. Plot the data.

<br><br>

::: {style="font-size: 0.875em;"}
[Back](/weeks/week-8.qmd) ⏎
:::