---
title: "Basics - Questionnaire"
engine: knitr
---

<br>

```{r}
#| echo: false
library(webexercises)
```

```{r}
#| class: webex-box
#| echo: false
#| results: asis
question <- "Which function is used to install packages in R?"
question_choices <- c(
    "`package_install()`",
    answer = "`install.packages()`",
    "`package_installation()`",
    "`library_install()`"
)
cat(question, longmcq(sample(question_choices)))
```

<br>

```{r}
#| class: webex-box
#| echo: false
#| results: asis
question <- "What is the correct syntax for creating a vector in R?"
question_choices <- c(
    "`vec(1, 2, 3)`",
    "`vector(1, 2, 3)`",
    answer = "`c(1, 2, 3)`",
    "`array(1, 2, 3)`"
)
cat(question, longmcq(sample(question_choices)))
```

<br>

```{r}
#| class: webex-box
#| echo: false
#| results: asis
question <- "To access the documentation for a specific function in R, you can use:"
question_choices <- c(
    answer = "`help(function_name)`",
    "`??function_name`",
    "`documentation(function_name)`",
    "`get_help(function_name)`"
)
cat(question, longmcq(sample(question_choices)))
```

<br>

```{r}
#| class: webex-box
#| echo: false
#| results: asis
question <- "Which symbol is used for assignment in R?"
question_choices <- c(
    "`~`",
    "`-`",
    "`<<`",
    answer = "`<-`"
)
cat(question, longmcq(sample(question_choices)))
```

<br>

```{r}
#| class: webex-box
#| echo: false
#| results: asis
question <- "What does the `class()` function in R do?"
question_choices <- c(
    "Returns the dimensions of an object",
    answer = "Returns the data type of an object",
    "Converts an object to a character type",
    "Checks if an object is empty"
)
cat(question, longmcq(sample(question_choices)))
```

<br>

```{r}
#| class: webex-box
#| echo: false
#| results: asis
question <- "Which function is used to generate a sequence of numbers in R?"
question_choices <- c(
    answer = "`seq()`",
    "`create_seq()`",
    "`range()`",
    "`generate_sequence()`"
)
cat(question, longmcq(sample(question_choices)))
```

<br>

```{r}
#| class: webex-box
#| echo: false
#| results: asis
question <- "In R, how do you check if a certain element exists in a vector?"
question_choices <- c(
    "`is_element()`",
    "`exists()`",
    "`in_vector()`",
    answer = "`%in%`"
)
cat(question, longmcq(sample(question_choices)))
```

<br>

```{r}
#| class: webex-box
#| echo: false
#| results: asis
question <- "What is the output of the following R code?\n
    x <- 10
    y <- 5
    result <- x * y
    print(result)
"
question_choices <- c(
    "`NULL`",
    "Error: unexpected 'print'",
    answer = "50",
    "The code does not produce any output"
)
cat(question, longmcq(sample(question_choices)))
```

<br>

```{r}
#| class: webex-box
#| echo: false
#| results: asis
question <- "The `data.frame()` function in R is used to create:"
question_choices <- c(
    "Matrices",
    answer = "Data frames",
    "Vectors",
    "Arrays"
)
cat(question, longmcq(sample(question_choices)))
```

<br>

```{r}
#| class: webex-box
#| echo: false
#| results: asis
question <- "What is the purpose of the `if-else` statement?"
question_choices <- c(
    answer = "To conditionally execute code based on a logical test",
    "To create a loop that repeats a block of code",
    "To define a function in R",
    "To assign a value to a variable"
)
cat(question, longmcq(sample(question_choices)))
```

<br>

```{r}
#| class: webex-box
#| echo: false
#| results: asis
question <- "Which operator is used to combine multiple conditions in an `if` statement?"
question_choices <- c(
    "`&`",
    "`+`",
    answer = "`&&`",
    "`%>%`"
)
cat(question, longmcq(sample(question_choices)))
```

<br>

```{r}
#| class: webex-box
#| echo: false
#| results: asis
question <- "What will be the output of the following `if-else` statement?\n
    x <- 5
    if (x < 3) {
        result <- 'small'
    } else {
        result <- 'large'
    }
    print(result)
"
question_choices <- c(
    "'small'",
    answer = "'large'",
    "'x < 3'",
    "Error: unexpected symbol"
)
cat(question, longmcq(sample(question_choices)))
```

<br>

```{r}
#| class: webex-box
#| echo: false
#| results: asis
question <- "In an `if-else` statement, if the condition in `if` is `FALSE`, and there is no `else` statement, what happens?"
question_choices <- c(
    "The program exits with an error",
    "The `if-else` statement automatically creates an `else` block",
    answer = "The program continues without executing the `if` block",
    "The program enters an infinite loop"
)
cat(question, longmcq(sample(question_choices)))
```

<br>

```{r}
#| class: webex-box
#| echo: false
#| results: asis
question <- "What is the primary purpose of a `for` loop in R?"
question_choices <- c(
    "To define a function",
    "To execute a block of code only once",
    "To repeat a block of code a specific number of times",
    answer = "To iterate over a sequence of values and perform operations"
)
cat(question, longmcq(sample(question_choices)))
```

<br>

```{r}
#| class: webex-box
#| echo: false
#| results: asis
question <- "What are the components of a `for` loop in R?"
question_choices <- c(
    "Initialization, condition, increment",
    "Start, end, step size",
    answer = "Sequence, variable, body of the loop",
    "Counter, iteration, operation"
)
cat(question, longmcq(sample(question_choices)))
```

<br>

```{r}
#| class: webex-box
#| echo: false
#| results: asis
question <- "In a `for` loop, how is the iteration variable typically updated?"
question_choices <- c(
    "It's incremented by 1 each time",
    answer = "It's assigned a new value from a sequence at each iteration",
    "It's multiplied by a constant factor",
    "It's decremented by 1 each time"
)
cat(question, longmcq(sample(question_choices)))
```

<br><br>

::: {style="font-size: 0.875em;"}
[Back](/weeks/week-1.qmd) ⏎
:::